---
kind: pipeline
type: kubernetes
name: Test

platform:
    os: linux
    arch: arm

steps:
  - name: rego:test
    image: golang:1.17-stretch
    commands:
      - go install github.com/open-policy-agent/opa@v0.38.0
      - opa test -v internal/policy/rego/
      - opa test -v internal/policy/testdata/

  - name: golang:test
    image: golang:1.17-stretch
    commands:
      # 'go test -race ...' not supported on ARM
      - go test -parallel=2 -v -coverprofile cover.out -count=1 ./...

  - name: golang:coverage:report
    image: golang:1.17-stretch
    commands:
      - go tool cover -func cover.out

  - name: react:test
    image: node:17.7-stretch
    commands:
      - cd ui
      - npm install
      - npm test -- --all --watchAll=false --coverage

  - name: react:build
    image: node:17.7-stretch
    commands:
      - cd ui
      - npm install
      - npm run build

---
kind: pipeline
type: kubernetes
name: Image Staging

depends_on:
- Test

platform:
  os: linux
  arch: arm

steps:
  - name: docker:staging
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      repo: cromrots/dndmachine
      tags: unstable
      cache_from: cromrots/dndmachine:cache
      cache_to: cromrots/dndmachine:cache
      password:
        from_secret: docker_pwd
      username:
        from_secret: docker_user

---
kind: pipeline
type: kubernetes
name: Image Production

trigger:
  event:
  - tag

depends_on:
- Image Staging

platform:
  os: linux
  arch: arm

steps:
  - name: docker:staging
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      repo: cromrots/dndmachine
      auto_tag: true
      cache_from: cromrots/dndmachine:cache
      cache_to: cromrots/dndmachine:cache
      password:
        from_secret: docker_pwd
      username:
        from_secret: docker_user

---
kind: pipeline
type: kubernetes
name: Notify Status

clone:
  disable: true

trigger:
  status:
  - success
  - failure

depends_on:
- Image Staging
- Image Production

platform:
  os: linux
  arch: arm

steps:
  - name: discord:notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      username: drone.io
      color: auto
      message: >
        <:dndmachine:855198423245389844> **{{repo.name}}**

        {{#success build.status}}
        :white_check_mark: {{build.event}} build {{build.number}} succeeded. Good job.
        {{else}}
        :warning: {{build.event}} build {{build.number}} failed. Fix me please.
        {{/success}}

        {{build.link}}

        **Branch:** {{commit.branch}} {{commit.tag}}

        **Message:** {{commit.message}}
---
kind: signature
hmac: 49e9458aca9dd56087d27a84567683237724e61ced9c956b77c8020c401cfa04

...
